
const TextBox = () => (
        <div className='text-box'>
            <h3> First Text Box </h3>
            <p> ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
                ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
                ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
                ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
                ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
                ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
                ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD ASDKOAKSD 
            </p>
        </div>
);

export default TextBox;